language: node_js
python:
  - "3.6"
node_js: stable

notifications:
  email:
    recipients:
      - hosiang969@sina.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm i

script:
  - npm install rimraf -g
  - rimraf node_modules


after_script:
  - git config user.name "Hosiang1026"
  - git config user.email "hosiang969@sina.com"
  - git init
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${CH_TOKEN}@${GH_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"


addons:
  apt:
    update: true

branches:
  only:
    - master

env:
 global:
   # Github Pages
   - GH_REF: github.com/Hosiang1026/zing-gallery
